package pipeline

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	"imprint/internal/llm"
	"imprint/internal/store"
)

const reflectSystemPrompt = `You are an insight generator. Analyze the provided memories and observations to find higher-order patterns, meta-insights, and actionable recommendations.

Look for:
- Recurring themes across different memories
- Contradictions or tensions between observations
- Workflow improvements suggested by the data
- Architectural patterns that emerge from file changes
- Common mistakes and their root causes

Respond with XML:
<insights>
  <insight>
    <title>Insight title (max 80 chars)</title>
    <content>Detailed insight with actionable recommendations</content>
    <confidence>0.0-1.0</confidence>
    <concepts><concept>concept</concept></concepts>
  </insight>
</insights>`

const reflectUserPrompt = `Analyze these %d memories and %d observations to generate higher-order insights:

Memories:
%s

Observations:
%s`

// ReflectedInsight represents an insight generated by the reflection pipeline.
type ReflectedInsight struct {
	Title      string   `json:"title"`
	Content    string   `json:"content"`
	Confidence float64  `json:"confidence"`
	Concepts   []string `json:"concepts"`
}

// Reflector generates insights from memories and observations via LLM.
type Reflector struct {
	provider llm.LLMProvider
}

// NewReflector creates a new Reflector with the given LLM provider.
func NewReflector(provider llm.LLMProvider) *Reflector {
	return &Reflector{provider: provider}
}

// Reflect generates insights from a set of memories and observations.
func (r *Reflector) Reflect(ctx context.Context, memories []store.MemoryRow, observations []store.CompressedObservationRow) ([]ReflectedInsight, error) {
	if len(memories) == 0 && len(observations) == 0 {
		return nil, nil
	}

	// Build memories section.
	var memSB strings.Builder
	for _, m := range memories {
		fmt.Fprintf(&memSB, "- [%s] %s (strength=%d): %s\n",
			m.Type, m.Title, m.Strength, truncate(m.Content, 200))
	}

	// Build observations section.
	var obsSB strings.Builder
	for _, obs := range observations {
		narrative := ""
		if obs.Narrative != nil {
			narrative = *obs.Narrative
		}
		concepts := strings.Join(obs.Concepts, ", ")
		fmt.Fprintf(&obsSB, "- [%s] %s: %s (concepts: %s)\n",
			obs.Type, obs.Title, narrative, concepts)
	}

	userPrompt := fmt.Sprintf(reflectUserPrompt,
		len(memories), len(observations),
		memSB.String(), obsSB.String())

	resp, err := r.provider.Complete(ctx, llm.CompletionRequest{
		SystemPrompt: reflectSystemPrompt,
		UserPrompt:   userPrompt,
		MaxTokens:    2000,
		Temperature:  0.4,
	})
	if err != nil {
		return nil, fmt.Errorf("LLM reflect: %w", err)
	}

	return parseReflectedInsights(resp), nil
}

// parseReflectedInsights extracts insights from the LLM XML response.
func parseReflectedInsights(resp string) []ReflectedInsight {
	insightsBlock := getXMLTag(resp, "insights")
	if insightsBlock == "" {
		insightsBlock = resp
	}

	blocks := splitXMLBlocks(insightsBlock, "insight")
	var result []ReflectedInsight

	for _, block := range blocks {
		title := getXMLTag(block, "title")
		if title == "" {
			continue
		}
		content := getXMLTag(block, "content")
		confidenceStr := getXMLTag(block, "confidence")
		confidence := parseFloat(confidenceStr, 0.5)
		if confidence < 0 {
			confidence = 0
		}
		if confidence > 1 {
			confidence = 1
		}
		concepts := getXMLChildren(block, "concepts", "concept")

		result = append(result, ReflectedInsight{
			Title:      title,
			Content:    content,
			Confidence: confidence,
			Concepts:   concepts,
		})
	}

	return result
}

// parseFloat parses a string as float64, returning defaultVal on failure.
func parseFloat(s string, defaultVal float64) float64 {
	s = strings.TrimSpace(s)
	if s == "" {
		return defaultVal
	}
	v, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return defaultVal
	}
	return v
}
